@startuml
class User {
  + username: String
  + age: int
}

class Photo {
  + image: ImageData
}

class WasteType {
  + name: String
  + relatedCategory: String
}

class "WasteRecognitionAPI" {
}

User "1" -- "*" Photo : uploads
Photo "1" -- "*" "WasteRecognitionAPI" : uses
Photo "1" -- "1" WasteType : determines
@enduml