= Besprechungsprotokoll 17.10.2023
firstname lastname
1.0, yyyy-mm-dd: Some notes
ifndef::imagesdir[:imagesdir: images]
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
//:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]


.Teilnehmer
|===
|anwesend

|Vorname Nachname
|B.Balint
|N. Said
|S.Erik
|B.Markus
|===

.Ort und Zeit
[cols=2*]
|===
|Ort
|Unterricht

|von-bis
|Di. 17.10.2023, 8 Einheit
|Dauer
|20 min
|===



== Besprochene Themen

* API ausprobieren +
alle ausprobieren REST APIs
* Use Case Diagramm +
    bis nächste woche

== Vereinbarungen und Entscheidungen

.Was wurde vereinbart?
[%autowidth]
|===
|wer |macht was |bis wann

| Balint
a| 3 Arten von APIs benutzen, entscheiden welche wir nehmen, oder ob das Projekt  überhaupt realisierbar ist ?

5 Gegenstände mit 3 APIs austesten und mit dokumentieren, eine Live demo ist möglich
| 7.11.2023