@startuml
left to right direction
actor "User" as cd
rectangle Leoenergy {
  usecase "Energieverbrauch einsehen" as energyConsumption
  usecase "Energieverkauf einsehen" as energySell
}
cd -- energyConsumption
cd -- energySell

@enduml