= Deployment Leoenergy

== Prerequisites
* Machine with https://ubuntu.com/tutorials/install-ubuntu-desktop#1-overview[Ubuntu 24.04]
* https://docs.docker.com/engine/install/ubuntu/[Docker Engine with Docker Compose]
* https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-20-04[Nginx]
* Files
** docker-compose.yaml
** grafana.ini

== Docker Compose

=== Services
* influxdb: our time-series database
** port mapped to 8086
* grafana: tool to create graphs from data in influxdb
** port mapped to 3000
* leoenergy: receives mqtt messages and writes data to influxdb
** port mapped to 8080
* frontend: display data, with embedded grafana boards
** port mapped to 8000

.docker-compose.yaml
[source, yaml]
----
include::files/docker-compose.yaml[]
----
<1> You can define username and password using environment-variables
<2> Bind mounting of influxdb data
<3> It's important to mount the data correctly using bind mounts. You also need grafana.ini file in the same directory as your docker-compose.yaml

=== Grafana Initialization File (grafana.ini)
IMPORTANT: You need grafana.ini file in the same directory as your docker-compose.yaml.

change follwing attributes to the options you need:

[source, ini]
----
http_port = 3000
domain = <server_domain_without_protocol>
enforce_domain = false
root_url = https://<server_domain>/grafana/
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = false
admin_user = <choose_admin_username>
admin_password = <choose_admin_password>
allow_embedding = true
enabled = true
----